server {
    listen 80;
    server_name localhost;
    root /var/www/html/public;

    index index.php index.html;

    # Static files
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        try_files $uri =404;
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }

    # Main handler
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP handler
    location ~ \.php$ {
        include fastcgi_params;

        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # Deny hidden files
    location ~ /\. {
        deny all;
    }
}